namespace: rob
name: test
version: 0.0.35
readme: README.md
authors:
  - Rob Harris <roharris@redhat.com>
description: Test collection to AH
license:
  - GPL-2.0-or-later
license_file: ''
tags: []
dependencies: {}
repository: http://example.com/repository
documentation: http://docs.example.com
homepage: http://example.com
issues: http://example.com/issue/tracker
build_ignore: []
