---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  collections:
    - rob.test
  tasks:
    - name: "Check file has been made"
      ansible.builtin.stat:
        path: "~/hello_world.txt"

    - name: "Cat the file contents"
      ansible.builtin.command: cat ~/hello_world.txt
      changed_when: false
      register: output

    - name: "Check the content"
      ansible.builtin.assert:
        that:
          - output.stdout == "Hello world from the Role within the collection in the file"
