---
galaxy_info:
  author: Rob Harris
  description: Role Test
  company: Tom Page Co

  license: MIT

  min_ansible_version: "2.11"

  platforms:
    - name: Fedora
      versions:
        - all

  galaxy_tags: []

dependencies: []
