---
name: Release on version

on: 
  push:
    tags:
      - "*"

jobs:

  update-galaxy-version:
    name: Update Galaxy Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: Push changes back to github
        run: |
          pip3 install yq --user
          yq -i -y '.version = "${{ github.ref_name }}"' ./galaxy.yml 

          git remote set-head origin --auto
          git checkout main
          git config --global user.name "Rob Harris"
          git config --global user.email "harrisrp95@gmail.com"

          git add -A
          git commit -m "Update Ansible Galaxy version"
          git push 

  super-lint:
    name: "Lint code base"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.repository }}/roles/hello_world"
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'

  test-yaml-reader:
    runs-on: ubuntu-latest
    name: Test read-yaml
    outputs:
      collection_name: ${{ steps.collection_name.outputs.name }}
      collection_namespace: ${{ steps.collection_namespace.outputs.namespace }}
    steps:
      - uses: actions/checkout@v3
      - name: gather env vars
        run: |
          pip3 install yq --user
          export COLLECTION_NAME=$(yq -r '.name' ./galaxy.yml)
          export COLLECTION_NAMESPACE=$(yq -r '.namespace' ./galaxy.yml)
          echo $COLLECTION_NAME
          echo $COLLECTION_NAMESPACE

      - name: Set collection name
        id: collection_name
        run: |
          echo $COLLECTION_NAME
          echo "name=$COLLECTION_NAME" >> $GITHUB_OUTPUT

      - name: Set collection namespace
        id: collection_namespace
        run: |
          echo $COLLECTION_NAMESPACE
          echo "namespace=$COLLECTION_NAMESPACE" >> $GITHUB_OUTPUT

      - name: Print out the GitHUB_OUTPUT 
        run: | 
          echo "name is ${{ steps.collection_name.outputs.collection_name }}"
          echo "namespace is ${{ steps.collection_namespace.outputs.collection_namespace }}"
