---
name: Release on version

on: 
  push:
    tags:
      - "v*"

jobs:
  update-galaxy-version:
    name: Update Galaxy Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "update galaxy version"
        uses: rmeneely/update-yaml@v1
        with:
          infile: "${{ github.repository }}/galaxy.yml"
          varlist: "version=v0.0.16"
      - name: Push the updated tag version to galaxy.yml
        uses: actions/checkout@v3
      - run: |
          git config user.name "Rob Harris"
          git config user.email harrisrp95@gmail.com
          git add "${{ github.repository }}/galaxy.yml"
          git commit -m "Updated galaxy version"
          git push

  super-lint:
    name: "Lint code base"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.repository }}/roles/hello_world"
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'