---
name: Release on version

on: 
  push:
    tags:
      - "v*"

jobs:
  update-galaxy-version:
    name: Update Galaxy Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.2

      - name: "update galaxy version"
        uses: rmeneely/update-yaml@v1
        with:
          infile: galaxy.yml
          varlist: "version=${{ github.ref_type	}}"

  super-lint:
    name: "Lint code base"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_working_dir: "${{ github.repository }}/roles/hello_world"
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'